// This file is auto-generated by opencollective-frontend/scripts/export-tax-form-types.ts

export enum TaxFormType {
  W9 = 'W9',
  W8_BEN = 'W8_BEN',
  W8_BEN_E = 'W8_BEN_E',
}

export enum SubmitterType {
  Individual = 'Individual',
  Business = 'Business',
}

export enum FederalTaxClassification {
  Individual = 'Individual',
  C_Corporation = 'C_Corporation',
  S_Corporation = 'S_Corporation',
  Partnership = 'Partnership',
  TrustEstate = 'TrustEstate',
  LimitedLiabilityCompany = 'LimitedLiabilityCompany',
  Other = 'Other',
}

export enum Chapter3Status {
  Corporation = 'Corporation',
  Partnership = 'Partnership',
  SimpleTrust = 'SimpleTrust',
  TaxExemptOrganization = 'TaxExemptOrganization',
  ComplexTrust = 'ComplexTrust',
  ForeignGovernmentControlledEntity = 'ForeignGovernmentControlledEntity',
  CentralBankOfIssue = 'CentralBankOfIssue',
  PrivateFoundation = 'PrivateFoundation',
  Estate = 'Estate',
  ForeignGovernmentIntegralPart = 'ForeignGovernmentIntegralPart',
  GrantorTrust = 'GrantorTrust',
  DisregardedEntity = 'DisregardedEntity',
  InternationalOrganization = 'InternationalOrganization',
}

export enum TypeOfLimitationOnBenefitsProvisions {
  Government = 'Government',
  TaxExemptPensionTrustOrPensionFund = 'TaxExemptPensionTrustOrPensionFund',
  OtherTaxExemptOrganization = 'OtherTaxExemptOrganization',
  PubliclyTradedCorporation = 'PubliclyTradedCorporation',
  SubsidiaryOfAPubliclyTradedCorporation = 'SubsidiaryOfAPubliclyTradedCorporation',
  CompanyThatMeetsTheOwnershipAndBaseErosionTest = 'CompanyThatMeetsTheOwnershipAndBaseErosionTest',
  CompanyThatMeetsTheDerivativeBenefitsTest = 'CompanyThatMeetsTheDerivativeBenefitsTest',
  CompanyWithAnItemOfIncomeThatMeetsActiveTradeOrBusinessTest = 'CompanyWithAnItemOfIncomeThatMeetsActiveTradeOrBusinessTest',
  FavorableDiscretionaryDeterminationByTheUSCompetentAuthorityReceived = 'FavorableDiscretionaryDeterminationByTheUSCompetentAuthorityReceived',
  NoLOBArticleInTreaty = 'NoLOBArticleInTreaty',
  Other = 'Other',
}

export enum NFFEStatus {
  ActiveNFFE = 'ActiveNFFE',
  PassiveNFFE = 'PassiveNFFE',
  NonProfitOrganization = 'NonProfitOrganization',
}

export type BaseFormValues = {
  isUSPersonOrEntity?: boolean;
  submitterType?: SubmitterType;
  formType?: TaxFormType;
  email?: string;
  signer?: { firstName?: string; middleName?: string; lastName?: string };
  isSigned?: boolean;
};

export type W9TaxFormValues = {
  isUSPersonOrEntity?: boolean;
  submitterType?: SubmitterType;
  formType?: TaxFormType;
  email?: string;
  signer?: { firstName?: string; middleName?: string; lastName?: string };
  isSigned?: boolean;
  organizationName?: string;
  businessName?: string;
  federalTaxClassificationDetails?: string;
  llcTaxClassification?: 'C' | 'S' | 'P' | '';
  exemptPayeeCode?: string;
  fatcaExemptionCode?: string;
  taxIdNumberType?: 'SSN' | 'EIN';
  taxIdNumber?: string;
  accountNumbers?: string;
  federalTaxClassification?: FederalTaxClassification;
  hasConfirmedTOS?: boolean;
  location?: {
    country?: string;
    structured?: { address1?: string; address2?: string; city?: string; zone?: string; postalCode?: string };
  };
};

export type W8BenTaxFormValues = ({
  isUSPersonOrEntity?: boolean;
  submitterType?: SubmitterType;
  formType?: TaxFormType;
  email?: string;
  signer?: { firstName?: string; middleName?: string; lastName?: string };
  isSigned?: boolean;
  hasConfirmedTOS?: boolean;
  beneficialOwner?: { firstName?: string; middleName?: string; lastName?: string };
  taxpayerIdentificationNumberTypeUS?: 'SSN' | 'ITIN';
  taxpayerIdentificationNumberUS?: string;
  taxpayerIdentificationNumberForeign?: string;
  dateOfBirth?: string;
  countryOfCitizenship?: string;
  residenceAddress?: {
    country?: string;
    structured?: { address1?: string; address2?: string; city?: string; zone?: string; postalCode?: string };
  };
  mailingAddress?: {
    country?: string;
    structured?: { address1?: string; address2?: string; city?: string; zone?: string; postalCode?: string };
  };
  claimsSpecialRatesAndConditions?: boolean;
  isSignerTheBeneficialOwner?: boolean;
  certifiesResidentCountry?: boolean;
  hasTaxTreatySpecialRatesAndConditions?: boolean;
  claimsArticleAndParagraph?: string;
  claimsRate?: number;
  claimsIncomeType?: string;
  claimsExplanation?: string;
  signerCapacity?: string;
} & ((
  | { claimsSpecialRatesAndConditions?: false }
  | {
      claimsSpecialRatesAndConditions?: true;
      certifiesResidentCountry?: boolean;
      hasTaxTreatySpecialRatesAndConditions?: boolean;
    }
) &
  (
    | { hasTaxTreatySpecialRatesAndConditions?: any }
    | { hasTaxTreatySpecialRatesAndConditions?: false }
    | {
        hasTaxTreatySpecialRatesAndConditions?: true;
        claimsArticleAndParagraph?: string;
        claimsRate?: number;
        claimsIncomeType?: string;
        claimsExplanation?: string;
      }
  ))) &
  ({ isSignerTheBeneficialOwner?: true } | { isSignerTheBeneficialOwner?: false; signerCapacity?: string });

export type W8BenETaxFormValues = ((({
  isUSPersonOrEntity?: boolean;
  submitterType?: SubmitterType;
  formType?: TaxFormType;
  email?: string;
  signer?: { firstName?: string; middleName?: string; lastName?: string };
  isSigned?: boolean;
  businessName?: string;
  hasConfirmedTOS?: boolean;
  taxpayerIdentificationNumberUS?: string;
  taxpayerIdentificationNumberForeign?: string;
  claimsSpecialRatesAndConditions?: boolean;
  claimsArticleAndParagraph?: string;
  claimsRate?: number;
  claimsIncomeType?: string;
  claimsExplanation?: string;
  businessCountryOfIncorporationOrOrganization?: string;
  businessAddress?: {
    country?: string;
    structured?: { address1?: string; address2?: string; city?: string; zone?: string; postalCode?: string };
  };
  businessMailingAddress?: {
    country?: string;
    structured?: { address1?: string; address2?: string; city?: string; zone?: string; postalCode?: string };
  };
  disregardedBusinessName?: string;
  chapter3Status?: Chapter3Status;
  hasCapacityToSign?: boolean;
  certifyStatus?: boolean;
  giin?: string;
  reference?: string;
  isHybridEntity?: boolean;
  nffeStatus?: NFFEStatus;
  certifyDerivesIncome?: boolean;
  typeOfLimitationOnBenefitsProvisions?: TypeOfLimitationOnBenefitsProvisions;
  typeOfLimitationOnBenefitsProvisionsOther?: string;
  certifyBeneficialOwnerCountry?: boolean;
  certifyForeignCorporation?: boolean;
  usOwners?: {
    name?: string;
    address?: {
      country?: string;
      structured?: { address1?: string; address2?: string; city?: string; zone?: string; postalCode?: string };
    };
    tin?: string;
  }[];
} & (
  | { nffeStatus?: NFFEStatus.ActiveNFFE }
  | { nffeStatus?: NFFEStatus.NonProfitOrganization }
  | {
      nffeStatus?: NFFEStatus.PassiveNFFE;
      usOwners?: {
        name?: string;
        address?: {
          country?: string;
          structured?: { address1?: string; address2?: string; city?: string; zone?: string; postalCode?: string };
        };
        tin?: string;
      }[];
      entityHasNoUSOwners?: boolean;
    }
)) &
  (
    | { isHybridEntity?: boolean }
    | {
        claimsSpecialRatesAndConditions?: boolean;
        isHybridEntity?: boolean;
        certifyDerivesIncome?: boolean;
        certifyBeneficialOwnerCountry?: boolean;
        certifyForeignCorporation?: boolean;
      }
  )) &
  (
    | { certifyDerivesIncome?: boolean }
    | { certifyDerivesIncome?: boolean }
    | {
        certifyDerivesIncome?: boolean;
        typeOfLimitationOnBenefitsProvisions?: TypeOfLimitationOnBenefitsProvisions;
        typeOfLimitationOnBenefitsProvisionsOther?: string;
      }
  )) &
  (
    | { claimsSpecialRatesAndConditions?: boolean }
    | { claimsSpecialRatesAndConditions?: boolean }
    | {
        claimsSpecialRatesAndConditions?: boolean;
        claimsArticleAndParagraph?: string;
        claimsRate?: number;
        claimsIncomeType?: string;
        claimsExplanation?: string;
      }
  );
